# PR Auto Labeler Configuration
# ファイルパスに基づいてラベルを自動付与
# 参考: https://github.com/actions/labeler
#
# 注意: ラベル名は「カテゴリ:内容」形式（コロン区切り）
# 例: area:frontend, tech:shadcn, scope:component

# =====================================
# 領域ラベル（area:）
# =====================================

area:frontend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/**'
          - 'src/components/**'
          - 'src/features/**/components/**'

area:backend:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/server/**'
          - 'src/pages/api/**'
          - 'src/lib/api/**'

area:database:
  - changed-files:
      - any-glob-to-any-file:
          - 'supabase/**'
          - 'prisma/**'
          - 'src/lib/supabase/**'

area:api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/server/routers/**'
          - 'src/pages/api/**'

area:ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/ui/**'
          - 'src/styles/**'

area:calendar:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/features/calendar/**'

area:auth:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/features/auth/**'

area:settings:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/features/settings/**'
          - 'src/app/**/settings/**'

area:search:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/features/search/**'

area:inbox:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/features/inbox/**'
          - 'src/app/**/inbox/**'

area:tag:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/features/tags/**'
          - 'src/app/**/tags/**'

# =====================================
# 技術スタックラベル（tech:）
# =====================================

tech:shadcn:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/ui/**'
          - 'components.json'

tech:tailwind:
  - changed-files:
      - any-glob-to-any-file:
          - 'tailwind.config.*'
          - 'src/styles/globals.css'
          - 'postcss.config.*'

tech:supabase:
  - changed-files:
      - any-glob-to-any-file:
          - 'supabase/**'
          - 'src/lib/supabase/**'
          - 'src/server/supabase/**'

tech:trpc:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/server/routers/**'
          - 'src/server/trpc/**'
          - 'src/lib/trpc/**'

tech:zustand:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/stores/**'
          - 'src/**/store.ts'
          - 'src/**/*Store.ts'

tech:nextjs:
  - changed-files:
      - any-glob-to-any-file:
          - 'next.config.*'
          - 'src/middleware.ts'
          - 'src/app/**'

tech:eslint:
  - changed-files:
      - any-glob-to-any-file:
          - '.eslintrc*'
          - 'eslint.config.*'

tech:vitest:
  - changed-files:
      - any-glob-to-any-file:
          - 'vitest.config.*'
          - 'src/**/*.test.ts'
          - 'src/**/*.test.tsx'
          - 'src/**/*.spec.ts'
          - 'src/**/*.spec.tsx'

tech:playwright:
  - changed-files:
      - any-glob-to-any-file:
          - 'playwright.config.*'
          - 'e2e/**'
          - 'tests/**'

# =====================================
# 変更対象ラベル（scope:）
# =====================================

scope:component:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**/*.tsx'
          - 'src/features/**/components/**/*.tsx'

scope:hook:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/hooks/**'
          - 'src/**/hooks/**'
          - 'src/**/use*.ts'

scope:util:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/lib/**'
          - 'src/utils/**'

scope:type:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/types/**'
          - 'src/**/*.d.ts'

scope:route:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/app/**/page.tsx'
          - 'src/app/**/layout.tsx'
          - 'src/app/**/route.ts'

scope:store:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/stores/**'
          - 'src/**/stores/**'
          - 'src/**/*Store.ts'

scope:api:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/server/routers/**'

# =====================================
# ツールラベル（tool:）
# =====================================

tool:ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**'
          - '.github/actions/**'

# =====================================
# ドキュメントラベル
# =====================================

type:docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
