# Crowdin設定ファイル
# Next.js i18n公式推奨の翻訳管理
#
# 参考: https://crowdin.github.io/crowdin-cli/

# プロジェクト設定
'project_id_env': 'CROWDIN_PROJECT_ID'
'api_token_env': 'CROWDIN_API_TOKEN'
'base_path': '.'
'base_url': 'https://api.crowdin.com'

# ファイル設定
files:
  # JSON翻訳ファイル
  - source: /src/lib/i18n/dictionaries/en.json
    translation: /src/lib/i18n/dictionaries/%two_letters_code%.json
    update_option: update_as_unapproved

  # Markdown翻訳ファイル（ドキュメント）
  - source: /docs/**/*.en.md
    translation: /docs/**/%original_file_name%.%two_letters_code%.md
    ignore:
      - /docs/README.md
      - /docs/**/CLAUDE.md
